"""
Build a tiny synthetic BIDS dataset under ``assets/sample_bids/``.

This is what powers the "Try with sample data" button on the home page —
it lets a researcher who just cloned the repo see a real dataset wired
through Browse Subjects, QC, and the viewer without configuring any
remote credentials.

The dataset is intentionally minimal:
  * 2 subjects (sub-01, sub-02)
  * 1-2 sessions per subject (ses-01, ses-02)
  * Each session has one anat T1w; sub-01/ses-01 also has a func bold
  * All NIfTI volumes are 4x4x4 (or 4x4x4x5 for bold) — valid NIfTI-1,
    a few hundred bytes each gzipped

Re-run after editing this script and commit the result:

    python scripts/build_sample_bids.py
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import nibabel as nib
import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "assets" / "sample_bids"

# Deterministic noise so re-running produces a clean diff (or none)
RNG = np.random.default_rng(seed=42)


def _write_nii(path: Path, shape: tuple[int, ...]) -> None:
    """Write a tiny valid NIfTI-1 .nii.gz at ``path``."""
    path.parent.mkdir(parents=True, exist_ok=True)
    data = RNG.integers(0, 4096, size=shape, dtype=np.int16)
    # 1mm isotropic for anat; bold uses TR=2s on the time axis
    affine = np.eye(4)
    img = nib.Nifti1Image(data, affine)
    if len(shape) == 4:
        img.header.set_zooms((1.0, 1.0, 1.0, 2.0))
    nib.save(img, str(path))


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n")


def build() -> None:
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True)

    # ----- top-level BIDS metadata -----
    _write_json(
        OUT_DIR / "dataset_description.json",
        {
            "Name": "BIDSHub Sample Dataset",
            "BIDSVersion": "1.6.0",
            "DatasetType": "raw",
            "Authors": ["BIDSHub demo"],
            "License": "CC0",
        },
    )

    (OUT_DIR / "README").write_text(
        "BIDSHub sample dataset (synthetic).\n\n"
        "Two subjects, tiny random NIfTI volumes. Generated by\n"
        "scripts/build_sample_bids.py. Safe to delete; the 'Try with\n"
        "sample data' button in BIDSHub points here.\n"
    )

    participants_tsv = (
        "participant_id\tage\tsex\tdiagnosis\tsite\n"
        "sub-01\t28\tM\tcontrol\tdemo-site-A\n"
        "sub-02\t34\tF\tTBI\tdemo-site-B\n"
    )
    (OUT_DIR / "participants.tsv").write_text(participants_tsv)

    _write_json(
        OUT_DIR / "participants.json",
        {
            "age": {"Description": "Age at scan (years)", "Units": "year"},
            "sex": {
                "Description": "Biological sex",
                "Levels": {"M": "male", "F": "female"},
            },
            "diagnosis": {
                "Description": "Primary diagnosis",
                "Levels": {"control": "healthy control", "TBI": "traumatic brain injury"},
            },
            "site": {"Description": "Acquisition site"},
        },
    )

    # ----- subjects -----
    # sub-01: two sessions, anat in both, func only in ses-01
    plan = {
        "sub-01": {
            "ses-01": [("anat", "T1w", (4, 4, 4)),
                       ("func", "task-rest_bold", (4, 4, 4, 5))],
            "ses-02": [("anat", "T1w", (4, 4, 4))],
        },
        "sub-02": {
            "ses-01": [("anat", "T1w", (4, 4, 4))],
        },
    }

    for sub, sessions in plan.items():
        for ses, scans in sessions.items():
            for modality, suffix, shape in scans:
                stem = f"{sub}_{ses}_{suffix}"
                base = OUT_DIR / sub / ses / modality / stem
                _write_nii(base.with_suffix(".nii.gz"), shape)

                sidecar = {
                    "EchoTime": 0.0025,
                    "RepetitionTime": 2.0 if "bold" in suffix else 2.3,
                    "Manufacturer": "Synthetic",
                    "MagneticFieldStrength": 3,
                }
                if "bold" in suffix:
                    sidecar["TaskName"] = "rest"
                _write_json(base.with_suffix(".json"), sidecar)

    # Count what we wrote so the build output is verifiable at a glance
    nii_count = sum(1 for _ in OUT_DIR.rglob("*.nii.gz"))
    json_count = sum(1 for _ in OUT_DIR.rglob("*.json"))
    print(f"wrote {nii_count} .nii.gz, {json_count} .json under {OUT_DIR.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    build()
