# PyInstaller spec for the BIDSHub desktop app (phase 3).
#
# The tricky part: Streamlit loads app.py *dynamically* at runtime, so
# PyInstaller's import graph (which starts at desktop/app.py) never sees the
# imports inside app.py and the src.* modules. We therefore:
#   - compile our own packages (src, scripts) as real modules via
#     collect_submodules, and
#   - bundle app.py / assets / .streamlit as data files so the running server
#     can read them from sys._MEIPASS, and
#   - collect_all the data-bearing third-party libs, and copy their metadata
#     (several read importlib.metadata.version at import time).
#
# Build from the repo root:  pyinstaller packaging/bidshub.spec --noconfirm
# Output: dist/BIDSHub/ (onedir) and, on macOS, dist/BIDSHub.app

import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_all, collect_submodules, copy_metadata

ROOT = Path(SPECPATH).resolve().parent  # SPECPATH = packaging/

# The spec lives in packaging/, so PyInstaller puts THAT on sys.path — not the
# repo root. Without this, `collect_submodules('src')` can't import `src` and
# returns nothing, so every src.* module that only app.py imports (src.theme,
# the platform agents, …) is silently left out of the bundle and the app dies
# at runtime with ModuleNotFoundError. Put the repo root on the path first.
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

datas = []
binaries = []
hiddenimports = []

# --- our app: data Streamlit reads at runtime + modules it imports ----------
datas += [
    (str(ROOT / "app.py"), "."),
    (str(ROOT / ".streamlit"), ".streamlit"),
    (str(ROOT / "assets"), "assets"),
]
# collect_submodules pulls in every src.*/scripts.* module; PyInstaller then
# follows each one's own imports, so their third-party deps come along too.
src_mods = collect_submodules("src")
assert "src.theme" in src_mods, "collect_submodules('src') failed — src not importable at spec eval"
hiddenimports += src_mods
hiddenimports += collect_submodules("scripts")
# Page modules extracted from app.py (loaded dynamically by Streamlit, so the
# import graph from desktop/app.py never sees them — collect explicitly).
hiddenimports += collect_submodules("views")
assert "views.dashboard" in hiddenimports, "collect_submodules('views') failed — views not importable at spec eval"
# Imported directly by app.py (which PyInstaller never analyses); harmless if
# already pulled in transitively via src.
hiddenimports += ["dotenv"]

# --- heavy / data-bearing third-party libs ---------------------------------
# NB: dandi pulls in dandischema/pynwb/hdmf/nwbinspector/bidsschematools, which
# ship JSON schema/resource files (e.g. dandischema/_resources/spdx_license_ids.json).
# collect_all('dandi') does NOT collect its dependencies' data, so without these
# `import dandi` raises FileNotFoundError in the frozen app and DANDI validation
# and sync silently fail. Collect the whole cluster's data.
THIRD_PARTY = [
    "streamlit", "bids", "nibabel", "pennsieve", "dandi", "xnat",
    "openneuro", "boto3", "paramiko", "pandas", "numpy", "requests",
    "dandischema", "pynwb", "hdmf", "nwbinspector", "bidsschematools",
]
for pkg in THIRD_PARTY:
    try:
        d, b, h = collect_all(pkg)
        datas += d
        binaries += b
        hiddenimports += h
    except Exception as exc:  # a missing optional lib must not abort the build
        print(f"[spec] collect_all({pkg!r}) skipped: {exc}")

# Distribution metadata some libraries read at import time.
for pkg in ["streamlit", "bids", "nibabel", "dandi", "pennsieve", "numpy",
            "pandas", "pyarrow", "altair", "click"]:
    try:
        datas += copy_metadata(pkg)
    except Exception as exc:
        print(f"[spec] copy_metadata({pkg!r}) skipped: {exc}")

# --- Linux: pywebview's GTK/WebKit2 backend via PyGObject -------------------
# pywebview imports gi.repository.* lazily at runtime, so PyInstaller's import
# graph never sees them and the gi hook can't know which GObject-Introspection
# typelibs/shared libs to bundle. Naming the namespaces explicitly makes the
# bundled gi hook collect the matching typelibs (Gtk-3.0, WebKit2-4.1, …).
if sys.platform.startswith("linux"):
    hiddenimports += [
        "gi",
        "gi.repository.Gtk",
        "gi.repository.Gdk",
        "gi.repository.GLib",
        "gi.repository.Gio",
        "gi.repository.GObject",
        "gi.repository.WebKit2",
        "gi.repository.Soup",
        "gi._gi_cairo",
        "cairo",
    ]
    try:
        d, b, h = collect_all("gi")
        datas += d
        binaries += b
        hiddenimports += h
    except Exception as exc:
        print(f"[spec] collect_all('gi') skipped: {exc}")

block_cipher = None

# App icons (generated by packaging/make_icons.py). Missing icons are fine —
# the build just ships without one.
ICON_DIR = ROOT / "packaging" / "icons"
ICNS = ICON_DIR / "BIDSHub.icns"
ICO = ICON_DIR / "BIDSHub.ico"
exe_icon = str(ICO) if (sys.platform == "win32" and ICO.exists()) else None
bundle_icon = str(ICNS) if ICNS.exists() else None

a = Analysis(
    [str(ROOT / "desktop" / "app.py")],
    pathex=[str(ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "pytest"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="BIDSHub",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,  # windowed app; diagnostics go to <data_dir>/logs/desktop.log
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=exe_icon,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="BIDSHub",
)

# macOS: wrap the onedir output in an .app bundle (icon added in phase 4).
if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name="BIDSHub.app",
        icon=bundle_icon,
        bundle_identifier="org.bidshub.desktop",
        info_plist={
            "CFBundleName": "BIDSHub",
            "CFBundleDisplayName": "BIDSHub",
            "NSHighResolutionCapable": True,
        },
    )
